# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
# SPDX-License-Identifier: MIT
apiVersion: v1
kind: Service
metadata:
  name: {{ include "metaldhcp.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "metaldhcp.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "metaldhcp.selectorLabels" . | nindent 4 }}
  ports:
    - name: dhcp
      port: 67
      protocol: UDP
      targetPort: 67
  type: LoadBalancer
  loadBalancerIP: {{ .Values.externalIP }}
  externalTrafficPolicy: Local
