name: Check Codegen

on:
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  check-codegen:
    name: Check generated code and manifests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run code and manifest generation
        run: make generate manifests fmt
      - name: Fail on uncommitted changes
        run: |
          if [ "$(git diff | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after generation. Run 'make generate manifests fmt' locally."
            git diff
            exit 1
          fi
